version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: 'java_orm'
      POSTGRES_PASSWORD: 'root'

    ports:
      - 5432:5432
    volumes:
      - my-db:/var/lib/postgres


volumes:
  my-db:
